name: sphinx

on: push

permissions:
  contents: write

jobs:
  docs:
    if: ${{ github.repository == 'onyx-robotics/onyx-engine' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
          pip install .
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          force_orphan: true